version: '3.8'

services:
  backend:
    build: ./server
    container_name: chat_backend
    ports:
      - '5000:5000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./client
    container_name: chat_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  redis:
    image: redis:alpine
    container_name: chat_solabor
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
